name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name
    - name: Run image
      run: docker run my-image-name google-chrome --headless --disable-gpu --remote-debugging-port=9222 https://www.chromestatus.com
